server:
  port: 8083
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: ACCOUNT_SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/account/**

        - id: CUSTOMER_SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/customer/**